### ISSUE TITLE
No ability to send the Event ID with Conversions

### ISSUE THREAD

**Issue by tgowing** [managed-components/twitter#3]
As you can see in the Documentation below from Twitter, we need the ability to send the pixel id and the specific event id. Currently there is no way to add the event id in cloudflare Twitter tool interface. So we can't track individual conversions. Is this going to be fixed soon?
![Screenshot 2023-05-10 at 7 10 17 pm](https://github.com/managed-components/twitter/assets/11142114/511cc8b2-2330-47e0-8845-d03a506b355d)

**Comment by bjesus** [comment]
Here too, before adding anything to the Cloudflare UI, we need to make sure the component knows what to do with this Event ID - where to expect it and how to send it. Once we have that, we will quickly update the UI to support entering this data.

**Comment by tgowing** [comment]
Hi @bjesus, after looking more closely at the code, it seems you are using the "ID Sync Integration" endpoint (https://developer.twitter.com/en/docs/twitter-ads-api/audiences/overview/id-sync). I was expecting you to use the Conversions API Endpoint (https://developer.twitter.com/en/docs/twitter-ads-api/measurement/web-conversions/conversion-api) . I'm hoping to be able to send specific events/conversions which doesn't appear possible with the ID Sync Integration. Is this right, are you thinking this sort of functionality is possible with the current setup?

**Comment by kuba-orlik** [comment]
Our current implementation does not use the server-side Conversion API. We're not going to implement this in this particular component, as it would require changes in the config that cannot be done automatically, thus migrating all existing users to that new version would be a no-go.

We're open to welcome a Conversion API-based managed component to the `managed-components` catalog if someone's interested in implementing it!

**Comment by tgowing** [comment]
@kuba-orlik @bjesus Is there any way to test the component in Cloudflare before being published in the `managed-components` catalog? We are considering creating one, following the [`facebook-pixel`](https://github.com/managed-components/facebook-pixel/tree/main/src) example. How can we test the code while developing it? Thank you!

**Comment by kuba-orlik** [comment]
@tgowing https://github.com/cloudflare/webcm is the answer - you can test it locally, as it implements the Managed Component manager API. Feel free to reach out if you have any questions on how to use it for local development!
